### ISSUE TITLE
grafana_datasource not idempotent

### ISSUE THREAD

**Issue by axxeo** [ansible-collections/grafana#67]
##### SUMMARY
Running the grafana_datasource module always (with same args) results in changed=True.
The check in line 597
`if ds.get('readOnly'): del ds['readOnly']`
yields False due to the value 'False' of the key 'readOnly', so the key won't be deleted. But the excepted behaviour would be to delete the key due to its existence. So the later check in line 609
`if ds == payload:`
yields False and therefore
`result['changed'] = True`
 instead of False.
The suggested fix would be
`if ds.has_key('readOnly'): del ds['readOnly']`

##### ISSUE TYPE
- Bug Report

**Comment by rrey** [comment]
Hi @axxeo !
Thanks for reporting this. Are you interested in submitting a patch ?

I checked the module tests and we have an idempotency test, can you give an example of code allowing to reproduce the issue ? (and the grafana version ?)
We need to add a test if we don't cover this case.

**Comment by axxeo** [comment]
Surely!

OS: Debian 10
Grafana Version 6.6.2 (commit: 3fa63cfc34, branch: HEAD)
influxdb  Version 1.7.10-1

Following the Code example:
The Ansible Task:
```
---
- name: Create grafana datasource
  grafana_datasource:
    name: "{{ item.name }}"
    access: "{{ item.access | default(omit) }}"
    basic_auth_password: "{{ item.basic_auth_password | default(omit) }}"
    basic_auth_user: "{{ item.basic_auth_user | default(omit) }}"
    client_cert: "{{ item.client_cert | default(omit) }}"
    client_key: "{{ item.client_key | default(omit) }}"
    database: "{{ item.database | default(omit) }}"
    ds_type: "{{ item.ds_type }}"
    es_version: "{{ item.es_version | default(omit) }}"
    grafana_api_key: "{{ item.grafana_api_key | default(omit) }}"
    grafana_url: "{{ item.grafana_url | default(grafana_url) }}"
    interval: "{{ item.interval | default(omit) }}"
    is_default: "{{ item.is_default | default(omit) }}"
    org_id: "{{ item.org_id | default(omit) }}"
    password: "{{ item.password | default(omit) }}"
    sslmode: "{{ item.sslmode | default(omit) }}"
    state: "{{ item.state | default('present') }}"
    tls_skip_verify: "{{ item.tls_skip_verify | default(grafana_datasource_tls_skip_verify) }}"
    url: "{{ item.url }}"
    url_username: "{{ item.url_username | default(grafana_admin_user) }}"
    url_password: "{{ item.url_password | default(grafana_admin_password) }}"
    user: "{{ item.user | default(omit) }}"
    validate_certs: "{{ item.validate_certs | default('no') }}"
    with_credentials: "{{ item.with_credentials | default(grafana_datasource_with_credentials) }}"
  loop: "{{ grafana_datasources }}"
```
Ansible Defaults:
```
---
grafana_url: "http://127.0.0.1:3000"
grafana_admin_user: "admin"
grafana_admin_password: "admin"
grafana_datasources: []
grafana_datasource_tls_skip_verify: true
grafana_datasource_with_credentials: true
```
Ansible Host Vars:
```
---
grafana_datasources:
  - name: "icinga2-influxdb"
    database: "icinga2"
    ds_type: "influxdb"
    password: "icinga2"
    url: "https://127.0.0.1:8086"
    user: "icinga2"
```
