### ISSUE TITLE
grafana_dashboard: can't override db after changed in GUI

### ISSUE THREAD

**Issue by CWollinger** [ansible-collections/grafana#76]
##### SUMMARY
Can't override existing DBs if changed with this "new" module (from collection grafana)
DB changed after export in GUI

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

grafana_dashboard

##### ANSIBLE VERSION

```paste below
ansible 2.9.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.17 (default, Nov  7 2019, 10:07:09) [GCC 7.4.0]

collection:
community.grafana 0.2.1
```

##### CONFIGURATION

```paste below
DEFAULT_KEEP_REMOTE_FILES(env: ANSIBLE_KEEP_REMOTE_FILES) = True
ENABLE_TASK_DEBUGGER(env: ANSIBLE_ENABLE_TASK_DEBUGGER) = True
```

##### OS / ENVIRONMENT

Ubuntu 18.04.3 LTS

##### STEPS TO REPRODUCE

1. Export an existing dashboard from your grafana via the module `state=export`
2. Change the dashboard via the GUI. E.g. duplicate a graph. 
3. Import the json (from step 1). Set `override=yes` and `state=present`

```yaml
---
- hosts: localhost
  collections:
    - community.grafana
  tasks:
  - name: Export dashboard
    grafana_dashboard:
      grafana_url: https://grafana.example.com
      grafana_api_key: "example"
      state: export
      uid: "Q9K5pvrWz"
      path: "/home/user/grafana/Q9K5pvrWz.json"


---
- hosts: localhost
  collections:
    - community.grafana
  tasks:
  - name: Import dashboard
    grafana_dashboard:
      grafana_url: https://grafana.example.com
      grafana_api_key: "example"
      state: present
      commit_message: Updated by ansible
      overwrite: yes
      path: "/home/user/grafana/Q9K5pvrWz.json"

```

##### EXPECTED RESULTS

The grafana dashboard should be overridden. 

This happens when you use the grafana_dashboard from the ansible 2.9 version.  

##### ACTUAL RESULTS

```paste below
ok: [localhost] => {
    "changed": false,
    "invocation": {
        "module_args": {
            "client_cert": null,
            "client_key": null,
            "commit_message": "Updated by ansible",
            "dashboard_id": null,
            "dashboard_revision": "1",
            "folder": "General",
            "grafana_api_key": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "grafana_url": "https://grafana.example.com",
            "org_id": 1,
            "overwrite": true,
            "path": "/home/user/grafana/Q9K5pvrWz.json",
            "slug": null,
            "state": "present",
            "uid": null,
            "url": "https://grafana.example.com",
            "url_password": "admin",
            "url_username": "admin",
            "use_proxy": true,
            "validate_certs": true
        }
    },
    "msg": "Dashboard Ansible unchanged.",
    "uid": "Q9K5pvrWz"
}

```

I found out that I will not reach the line 288 in the grafana_dashboard_changed def: https://github.com/ansible-collections/grafana/blob/243ee4a8e14a56d21dddf73c8ae52747e0b9e21c/plugins/modules/grafana_dashboard.py#L288
