### ISSUE TITLE
grafana_folder: unable to use spaces or other utf-8 chars in name/title

### ISSUE THREAD

**Issue by CWollinger** [ansible-collections/grafana#78]
##### SUMMARY

grafana_folder: unable to use spaces or other utf-8 chars in name/title

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

grafana_folder

##### ANSIBLE VERSION

```paste below
ansible 2.9.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.17 (default, Nov  7 2019, 10:07:09) [GCC 7.4.0]

collection:
community.grafana 0.2.1
```

##### CONFIGURATION

```paste below
DEFAULT_KEEP_REMOTE_FILES(env: ANSIBLE_KEEP_REMOTE_FILES) = True
```

##### OS / ENVIRONMENT

Ubuntu 18.04.3 LTS

##### STEPS TO REPRODUCE

Try to use space or äöü in title for the folder

```yaml
---
- hosts: localhost
  collections:
    - community.grafana
  tasks:
  - name: Export dashboard
    grafana_folder:
      grafana_url: https://grafana.example.com
      grafana_api_key: "..."
      state: present
      title: "{{ item }}"
    with_items:
      - Test DB 1
      - Test DB Ä
      - TEST DB ʦ
      - TEST DB ɮ
      - TEST DB Ŕ
      - TEST DB ‰
```

##### EXPECTED RESULTS

Folder should be created.

##### ACTUAL RESULTS

Error, because not URL quote for the get_folder API query.

```paste below
msg": "Grafana Folders API answered with HTTP -1"
```
